version: "3.3"
services:
  database:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: dashboard
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: 12345
    networks:
      - overlay
  databaseadmin:
    depends_on:
     - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: database
    networks:
      - overlay
  webapi:
    depends_on:
      - database
      - jaeger
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8081:8081
      - 9991:9991
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: dashboard
      DB_USER: root
      DB_PWD: 12345
      API_PORT: 8081
      API_HOST: localhost
      JAEGER_AGENT_HOST: jaeger
    volumes:
      - ./api:/app
    networks:
      - overlay
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - overlay
  spa:
    depends_on:
      - webapi
    build:
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      REACT_APP_API_HOST: localhost
      REACT_APP_API_PORT: 85
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
    networks:
      - overlay
  redis-exporter:
    image: bitnami/redis-exporter:latest
    ports:
      - 9121:9121
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on: 
      - redis
    networks:
      - overlay
  mysql-exporter:
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    environment: 
      - DATA_SOURCE_NAME=root:12345@(database:3306)/
      - collect.info_schema.tablestats=true
      - collect.info_schema.userstats=true
      - collect.info_schema.query_response_time=true
      - collect.auto_increment.columns=true
      - collect.binlog_size=true
      - collect.perf_schema.eventsstatements=true
      - collect.perf_schema.eventswaits=true
      - collect.perf_schema.file_events=true
      - collect.perf_schema.indexiowaits=true
      - collect.perf_schema.tableiowaits=true
      - collect.perf_schema.tablelocks=true
    depends_on: 
      - database
    networks:
      - overlay
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.route-prefix=/metrics
    - --web.external-url=http://prometheus:9090/metrics
    networks:
      - overlay
    depends_on: 
      - mysql-exporter
      - redis-exporter
      - webapi
  grafana:
    image: grafana/grafana
    ports:
      - '80:3000'
    volumes:
    - ./observability/grafana/config.ini:/etc/grafana/grafana.ini
    - ./observability/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - ./observability/grafana/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml
    - ./observability/grafana/dashboards:/etc/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: "root"
      GF_SECURITY_ADMIN_PASSWORD: "12345"
    networks:
      - overlay
    depends_on: 
      - prometheus
  reverseproxy:
    image: nginx
    ports:
      - '85:80'
    volumes:
    - ./reverseproxy/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./reverseproxy/architecture.html:/usr/share/nginx/html/architecture.html
    networks:
      - overlay
    depends_on: 
      - spa
      - grafana
      - keycloak
  dbkeycloak:
    image: mysql:5.7
    volumes:
      - db_data_kc:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: dbkeycloak
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: 12345
    networks:
      - overlay
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: dbkeycloak
      DB_DATABASE: dbkeycloak
      DB_USER: adminuser
      DB_PASSWORD: 12345
      KEYCLOAK_USER: adminuser
      KEYCLOAK_PASSWORD: 12345
      PROXY_ADRESS_FORWARDING: 'true'
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.migration.dir=/opt/jboss/keycloak/imports"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/themes/dashboards-keycloak-theme:/opt/jboss/keycloak/themes/dashboards-keycloak-theme
      - ./keycloak/scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    restart: always
    ports:
      - 8543:8080
    depends_on:
      - database
    networks:
      - overlay
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268/udp"
    restart: on-failure
    networks:
      - overlay
    environment: 
      QUERY_BASE_PATH: "/traces"
volumes:
  app:
  db_data:  
    driver: local
  db_data_kc:  
    driver: local
networks:
  overlay:
