{
 "title": "MySQL InnoDB Metrics",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(alias)" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "InnoDB Checkpoint Age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_checkpoint_age{alias=\"$host\"}",
     "legendFormat": "Uncheckpointed Bytes",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_checkpoint_age%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-24%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_checkpoint_max_age{alias=\"$host\"}",
     "legendFormat": "Max Checkpoint Age",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_checkpoint_age%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-24%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{alias=\"$host\"}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_variables_innodb_buffer_pool_size%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243201s%22%2C%22end_input%22%3A%222015-9-3%206%3A28%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Buffer Pool Size of Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(mysql_global_variables_innodb_buffer_pool_size{alias=\"$host\"} * 100) / on (alias) node_memory_MemTotal{alias=\"$host\"}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22(mysql_global_variables_innodb_buffer_pool_size%7Balias%3D%5C%22%24host%5C%22%7D%20*%20100)%20%2F%20on%20(alias)%20node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A15%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_max_trx_id{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_max_trx_id{alias=\"$host\"}[5m])",
     "legendFormat": "InnoDB Transactions",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_max_trx_id%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_history_list_length{alias=\"$host\"} or mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{alias=\"$host\"}",
     "legendFormat": "History Length",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_history_list_length%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243201s%22%2C%22end_input%22%3A%222015-9-18%2013%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_max_purge_lag{alias=\"$host\"}",
     "legendFormat": "Max Purge Lag",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_history_list_length%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243201s%22%2C%22end_input%22%3A%222015-9-18%2013%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Row Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{alias=\"$host\"}[5m])",
     "legendFormat": "Rows {{ operation }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_row_ops_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-27%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Log File Usage Hourly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_innodb_os_log_written{alias=\"$host\"}[1h])",
     "legendFormat": "Data Written",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_row_ops_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-27%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_log_files_in_group{alias=\"$host\"} * mysql_global_variables_innodb_log_file_size{alias=\"$host\"}",
     "legendFormat": "Total Size of InnoDB Log Files",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_row_ops_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-27%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_reads{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{alias=\"$host\"}[5m])",
     "legendFormat": "Data Reads",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_max_trx_id%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_writes{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{alias=\"$host\"}[5m])",
     "legendFormat": "Data Writes",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_max_trx_id%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_fsyncs{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{alias=\"$host\"}[5m])",
     "legendFormat": "Data Fsyncs",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_max_trx_id%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_log_writes{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_writes{alias=\"$host\"}[5m])",
     "legendFormat": "Log Writes",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_history_list_length%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243201s%22%2C%22end_input%22%3A%222015-9-18%2013%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_lock_waits{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_lock_waits{alias=\"$host\"}[5m])",
     "legendFormat": "Row Lock Waits",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_time{alias=\"$host\"}[$interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{alias=\"$host\"}[5m])/1000",
     "legendFormat": "Row Lock Wait Load"
    },
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_time{alias=\"$host\"}[$interval])/rate(mysql_global_status_innodb_row_lock_waits{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_lock_time{alias=\"$host\"}[5m])/irate(mysql_global_status_innodb_row_lock_waits{alias=\"$host\"}[5m])",
     "legendFormat": "Avg Row Lock Wait Time"
    }
   ]
  },
  { "title": "Buffer Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "InnoDB Buffer Pool Content",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{alias=\"$host\"}",
     "legendFormat": "Data Total",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty{alias=\"$host\"}",
     "legendFormat": "Data Dirty",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_buffer_pool_pages{alias=\"$host\", state!=\"dirty\"}",
     "legendFormat": "{{ state }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_pages_created{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_created{alias=\"$host\"}[5m])",
     "legendFormat": "Pages Created",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_pages_created%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_pages_read{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{alias=\"$host\"}[5m])",
     "legendFormat": "Pages Read",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_pages_read%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_pages_written{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_written{alias=\"$host\"}[5m])",
     "legendFormat": "Pages Written",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_pages_written%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{alias=\"$host\"}[5m])",
     "legendFormat": "Read Requests",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_row_ops_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-27%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{alias=\"$host\"}[5m])",
     "legendFormat": "Write Requests",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_row_ops_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-27%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  { "title": "Change/Insert Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "InnoDB Change Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_ibuf_segment_size{alias=\"$host\"} * mysql_global_status_innodb_page_size{alias=\"$host\"}",
     "legendFormat": "Allocated",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_checkpoint_age%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-24%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(mysql_global_status_innodb_ibuf_segment_size{alias=\"$host\"} - mysql_global_status_innodb_ibuf_free_list{alias=\"$host\"})*mysql_global_status_innodb_page_size{alias=\"$host\"}",
     "legendFormat": "Used",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_checkpoint_age%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-24%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Change Buffer Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merges{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merges{alias=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{alias=\"$host\"}[5m])",
     "legendFormat": "Merges",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_pages_created%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merged_inserts{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_inserts{alias=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{alias=\"$host\"}[5m])",
     "legendFormat": "Merged Inserts",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_pages_read%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merged_deletes{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_deletes{alias=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{alias=\"$host\"}[5m])",
     "legendFormat": "Merged Deletes",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_pages_read%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_ibuf_merged_delete_marks{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_delete_marks{alias=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{alias=\"$host\"}[5m])",
     "legendFormat": "Merged Delete Marks",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_pages_read%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "InnoDB Log Buffer Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_current{alias=\"$host\"}*0 + mysql_global_variables_innodb_log_buffer_size{alias=\"$host\"}",
     "legendFormat": "Size",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_current{alias=\"$host\"} - mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{alias=\"$host\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Change Buffer Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{alias=\"$host\"}[5m])",
     "legendFormat": "Ibuf Insert",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{alias=\"$host\"}[5m])",
     "legendFormat": "Ibuf Delete"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{alias=\"$host\"}[5m])",
     "legendFormat": "Ibuf Delete Mark"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{alias=\"$host\"}[5m])",
     "legendFormat": "Ibuf Merges"
    },
    {
     "expr": "(rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{alias=\"$host\"}[$interval])+rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{alias=\"$host\"}[$interval])+rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{alias=\"$host\"}[$interval]))/rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{alias=\"$host\"}[$interval]) or (irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{alias=\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{alias=\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{alias=\"$host\"}[5m]))/irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{alias=\"$host\"}[5m])",
     "legendFormat": "Ibuf Merge Ratio"
    }
   ]
  },
  {
   "title": "InnoDB Purge Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_purge_purge_upd_exist_or_extern_records_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_upd_exist_or_extern_records_total{alias=\"$host\"}[5m])",
     "legendFormat": "Updates Purged",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_purge_purge_del_mark_records_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_del_mark_records_total{alias=\"$host\"}[5m])",
     "legendFormat": "Deletes Purged"
    },
    {
     "expr": "rate(mysql_info_schema_innodb_metrics_purge_purge_undo_log_pages_total{alias=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_undo_log_pages_total{alias=\"$host\"}[5m])",
     "legendFormat": "Pages Purged"
    }
   ]
  },
  {
   "title": "InnoDB Group Commit Batch Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total[$interval])/rate(mysql_global_status_innodb_log_writes[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total[5m])/irate(mysql_global_status_innodb_log_writes[5m])",
     "legendFormat": "Group Commit Batch Size",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22mysql_global_status_innodb_buffer_pool_pages_data%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-2%207%3A21%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}