{
 "title": "Summary Dashboard",
 "tags": [
  "OS",
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(alias)" }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu{alias=\"$host\"}[$interval])) by (mode) * 100 / count_scalar(node_cpu{mode=\"user\", alias=\"$host\"}) or sum(irate(node_cpu{alias=\"$host\"}[5m])) by (mode) * 100 / count_scalar(node_cpu{mode=\"user\", alias=\"$host\"})",
     "legendFormat": "{{ mode }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%20by%20(mode)%20*%20100%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{alias=\"$host\"}",
     "legendFormat": "Processes in runnable state",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{alias=\"$host\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes{alias=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes{alias=\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Inbound",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes{alias=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes{alias=\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Outbound",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{alias=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{alias=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{alias=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{alias=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_read_time_ms{device!~\"dm-.+\", alias=\"$host\"}[$interval]) / rate(node_disk_reads_completed{device!~\"dm-.+\", alias=\"$host\"}[$interval])) or (irate(node_disk_read_time_ms{device!~\"dm-.+\", alias=\"$host\"}[5m]) / irate(node_disk_reads_completed{device!~\"dm-.+\", alias=\"$host\"}[5m]))",
     "legendFormat": "Read: {{ device }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(node_disk_read_time_ms%7Balias%3D%5C%22%24host%5C%22%7D%5B5m%5D)%20%2F%20rate(node_disk_reads_completed%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%209%3A12%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_write_time_ms{device!~\"dm-.+\", alias=\"$host\"}[$interval]) / rate(node_disk_writes_completed{device!~\"dm-.+\", alias=\"$host\"}[$interval])) or (irate(node_disk_write_time_ms{device!~\"dm-.+\", alias=\"$host\"}[5m]) / irate(node_disk_writes_completed{device!~\"dm-.+\", alias=\"$host\"}[5m]))",
     "legendFormat": "Write: {{ device }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(node_disk_write_time_ms%7Balias%3D%5C%22%24host%5C%22%7D%5B5m%5D)%20%2F%20rate(node_disk_writes_completed%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%209%3A12%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  { "title": "MySQL Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "MySQL Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_queries{alias=\"$host\"}[$interval]) or irate(mysql_global_status_queries{alias=\"$host\"}[5m])",
     "legendFormat": "Queries",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_row_ops_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-27%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "InnoDB Row Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{alias=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{alias=\"$host\"}[5m])",
     "legendFormat": "Rows {{ operation }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_innodb_row_ops_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-27%2010%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Top MySQL Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{alias=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{alias=\"$host\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_commands_total%7Bcommand%3D%5C%22select%5C%22%2C%20alias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243201s%22%2C%22end_input%22%3A%222015-9-18%2015%3A28%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Top MySQL Handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_handlers_total{alias=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_handlers_total{alias=\"$host\"}[5m])>0)",
     "legendFormat": "{{ handler }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_handler_read_rnd_next%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-8-20%2016%3A0%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}