{
 "title": "Cross Server Graphs",
 "tags": [
  "Percona",
  "OS",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(alias)" }
  ]
 },
 "panels": [
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_connections{alias=~\"$host\"}[$interval]) or irate(mysql_global_status_connections{alias=~\"$host\"}[5m])",
     "legendFormat": "{{ alias }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_connections%5B5m%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-10-6%207%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "MySQL Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_queries{alias=~\"$host\"}[$interval]) or irate(mysql_global_status_queries{alias=~\"$host\"}[5m])",
     "legendFormat": "{{ alias }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_queries%5B5m%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%209%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{alias=~\"$host\"}",
     "legendFormat": "{{ alias }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(node_memory_MemTotal{alias=~\"$host\"} - (node_memory_MemAvailable{alias=~\"$host\"} or (node_memory_MemFree{alias=~\"$host\"} + node_memory_Buffers{alias=~\"$host\"} + node_memory_Cached{alias=~\"$host\"}))) / node_memory_MemTotal{alias=~\"$host\"} * 100",
     "legendFormat": "{{ alias }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "MySQL Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_bytes_received{alias=~\"$host\"}[$interval]) + rate(mysql_global_status_bytes_sent{alias=~\"$host\"}[$interval])) or (irate(mysql_global_status_bytes_received{alias=~\"$host\"}[5m]) + irate(mysql_global_status_bytes_sent{alias=~\"$host\"}[5m]))",
     "legendFormat": "{{ alias }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22rate(mysql_global_status_bytes_received%7Balias%3D%5C%22%24host%5C%22%7D%5B5m%5D)%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2015%3A34%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes{alias=~\"$host\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_bytes{alias=~\"$host\", device!=\"lo\"}[$interval])) by (alias) or sum(irate(node_network_receive_bytes{alias=~\"$host\", device!=\"lo\"}[5m]) + irate(node_network_transmit_bytes{alias=~\"$host\", device!=\"lo\"}[5m])) by (alias)",
     "legendFormat": "{{ alias }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "MySQL Info",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_version_info{alias=~\"$host\"}",
     "legendFormat": "{{ alias }} | {{ version }} | {{ version_comment }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_uname_info%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2014%3A44%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "System Info",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_uname_info{alias=~\"$host\"}",
     "legendFormat": "{{ alias }} | Hostname: {{ nodename }} | Kernel: {{ release }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_uname_info%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2014%3A44%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}