global:
    scrape_interval: 15s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'mysql-exporter'
      static_configs:
          - targets: ['mysql-exporter:9104']
    - job_name: 'webapi'
      static_configs:
          - targets: ['webapi:8081']
    - job_name: 'redis-exporter'
      static_configs:
          - targets: ['redis-exporter:9121']